GeoDirectory/geodirectory

- change_log.txt
- geodirectory-assets/css/map.css
- geodirectory-functions/ajax_handler_functions.php
- geodirectory-functions/location_functions.php
- geodirectory-functions/map-functions/js/map.js
- geodirectory-functions/map-functions/map_template_tags.php
- On home page map css class added to highlight searched post type - FIXED
- Popular category count not working with ajax - FIXED
> On home page map css class added to highlight searched post type - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/listing_filters.php
- In backend geodirectory style conflicts with some themes style - FIXED
- Sort by most reviews not working in widget and shortcode popular post view - FIXED
> Some issues fixed

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- geodirectory-admin/admin_install.php
- geodirectory-functions/comments_functions.php
- geodirectory-functions/custom_taxonomy_hooks_actions.php
- geodirectory-widgets/geodirectory_bestof_widget.php
- geodirectory-widgets/listing_map_widget.php
- geodirectory_hooks_actions.php
- geodirectory_shortcodes.php
- Validation added for custom permalinks in GD -> General -> Permalinks - FIXED
- All Listings virtual page removed - CHANGED
- Shortcode added for best of widget - ADDED
- Recent reviews widget ratings stars color not changed with multirating color setting - FIXED
> Some bugs fixed

- change_log.txt
- geodirectory-assets/css/style.css
- geodirectory-functions/general_functions.php
- geodirectory-functions/shortcode_functions.php
- geodirectory_shortcodes.php
- Shortcode added for to display GeoDirectoy Listings with pagination - ADDED
> Shortcode added for to display GeoDirectoy Listings with pagination - ADDED

- change_log.txt
- geodirectory_shortcodes.php
- Marker cluster not working in maps added via shortcode - FIXED
> Marker cluster not working in maps added via shortcode - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-templates/listing-filter-form.php
- geodirectory_template_tags.php
- Awesome font upgraded with new Awesome font version 4.3.0 - ADDED
- After searching for a city not able to search city again without clearing Near input box - FIXED
> Some bug fixes

- change_log.txt
- geodirectory-functions/custom_functions.php
- geodirectory-functions/custom_taxonomy_hooks_actions.php
- geodirectory-functions/google_analytics.php
- geodirectory-functions/listing_filters.php
- On search pages sort options removed as sorting is done by search criteria - CHANGED
- Some DocBlocks added
> Some DocBlocks added & one bug fixed

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/taxonomy_functions.php
- New filter added for term link in popular category widget - ADDED
- Validation added to avoid multiple times selection for same category - FIXED
> Some bug fixed

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/location_functions.php
- geodirectory-widgets/listing_map_widget.php
- geodirectory_hooks_actions.php
- geodirectory_template_tags.php
- Some changes to to remove location filter for non location CPT listing
> Some changes to to remove location filter for non location CPT listing

- change_log.txt
- geodirectory-functions/listing_filters.php
- Searching function updated to find results for only matching whole words - FIXED
- REGEX replaced with wildcard(%) in search query
> Searching function updated to find results for only matching whole words - FIXED

- geodirectory-admin/admin_functions.php
- geodirectory-functions/location_functions.php
- csv upload default post location fixed
> csv upload default post location fixed

- geodirectory_shortcodes.php
> search shortcode modified

- geodirectory-templates/listing-listview.php
- geodirectory-templates/widget-listing-listview.php
Adding new actions to allow developers more flexibility in placing new content on widgets without having to replace the templates, which can only be done by 1 plugin, whereas this allows more flexibility.
> Add new actions inside of the listview and widget-listview templates

- change_log.txt
- geodirectory-assets/js/listing_validation_admin.js
- geodirectory-functions/map-functions/js/map.js
- Without filling mandatory fields click on save draft button keeps spinning - FIXED
- Autozoom assigned only for more then map markers - CHANGED
> Some bugs fixed & changes - FIXED

- change_log.txt
- geodirectory-functions/listing_filters.php
- With WPML search results listings for all languages - FIXED
> With WPML search results listings for all languages - FIXED

- change_log.txt
- geodirectory-templates/reg_frm.php
- In registration send password to email note removed when user allowed choose own password - FIXED
> In registration send password to email note removed when user allowed choose own password - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- Fields is_featured, package_id & expire_date do not working for import/export - FIXED
> Fields is_featured, package_id & expire_date do not working for import/export - FIXED

- change_log.txt
- geodirectory-functions/custom_functions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/post_functions.php
- geodirectory-functions/signup_function.php
- geodirectory-templates/login_frm.php
- geodirectory_shortcodes.php
- The recent reviews shortcode is missing the title attribute - FIXED
- Login error on GD signup page is not appearing - FIXED
- In forgot password notification user display name is not well formatted - FIXED
- Wrong link passed in send enquiry notification email - FIXED
> Bugs fixed

- change_log.txt
- geodirectory-admin/option-pages/design_settings_array.php
- geodirectory-functions/shortcode_functions.php
- geodirectory_template_tags.php
- Option added to customize pagination with "Showing results x-y of z" - ADDED
> Option added to customize pagination with "Showing results x-y of z" - ADDED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- Post images and location details not translated with WPML duplicate option - FIXED
> Post images and location details not translated with WPML duplicate option - FIXED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/signup_function.php
- Shortcodes [#username#] & [#user_login#] added in registration notification - FIXED
> Shortcodes [#username#] & [#user_login#] added in registration notification - FIXED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-widgets/geodirectory_bestof_widget.php
- Some filters added in best of widget - CHANGED
> Some filters added in best of widget - CHANGED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-widgets/geodirectory_popular_widget.php
- geodirectory_shortcodes.php
- Option added in popular post category widget to set default posttype - CHANGED
> Option added in popular post category widget to set default posttype - CHANGED

- change_log.txt
- geodirectory-admin/admin_functions.php
- Recurring events no working with GD import & export - FIXED
> Recurring events no working with GD import & export - FIXED

- change_log.txt
- geodirectory-functions/taxonomy_functions.php
- Category limit no longer counting child categories - FIXED
> Category limit no longer counting child categories - FIXED

- change_log.txt
- geodirectory-functions/general_functions.php
In popular post widget View All link in not correct if location filter disabled - FIXED
> In popular post widget View All link in not correct if location filter disabled - FIXED

- change_log.txt
- geodirectory-templates/reg_frm.php
- Conflicts due to same id for password field in login and register form - FIXED
> Conflicts due to same id for password field in login and register form - FIXED

- change_log.txt
- geodirectory_hooks_actions.php
- Editing CPT tag not updating tag for associated CPT listing - FIXED
> Editing CPT tag not updating tag for associated CPT listing - FIXED

- change_log.txt
- geodirectory-functions/post_functions.php
- New action "geodir_infowindow_meta_before" added in map marker info window - ADDED
> New action "geodir_infowindow_meta_before" added in map marker info window - ADDED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-functions/listing_filters.php
- Default category can be set by "default_category" in csv import - CHANGED
- Search unable to find listings for a particular keyword in the content - FIXED
> Default category can be set by "default_category" in csv import - CHANGED

- change_log.txt
- geodirectory-functions/custom_functions.php
- geodirectory_hooks_actions.php
- Yoast meta title, description & keywords now also works with %location% tag - ADDED
> Yoast meta title, description & keywords now also works with %location% tag - ADDED

- change_log.txt
- geodirectory-admin/option-pages/permalink_settings_array.php
- geodirectory-functions/custom_functions.php
- geodirectory-functions/custom_taxonomy_hooks_actions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/taxonomy_functions.php
- Options added for location specific urls like /country/city/ & /region/city/ - ADDED
> Options added for location specific urls like /country/city/ & /region/city/ - ADDED

- change_log.txt
- geodirectory-admin/admin_functions.php
- Custom field type fieldset should not import/export in csv file - FIXED
> Custom field type fieldset should not import/export in csv file - FIXED

- change_log.txt
- geodirectory-functions/post_functions.php
- Able to get WP_Error on post save failure in geodir_save_listing() - CHANGED
> Able to get WP_Error on post save failure in geodir_save_listing() - CHANGED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/template_functions.php
- geodirectory-templates/listing-listview.php
- geodirectory-templates/widget-listing-listview.php
- geodirectory_hooks_actions.php
- geodirectory_template_actions.php
- New actions added to customize listing not found message - CHANGED
> New actions added to customize listing not found message - CHANGED

- change_log.txt
- geodirectory_template_tags.php
- Pagination not working when location selected - FIXED
> Pagination not working when location selected - FIXED

- change_log.txt
- geodirectory-functions/template_functions.php
- geodirectory_shortcodes.php
- geodirectory_template_actions.php
- Shortcode added for CPT categories widget - ADDED
- Breadcrumb HTML does not wrap correctly for a small screens or in a mobile - FIXED
> Shortcode added for CPT categories widget - ADDED

- change_log.txt
- geodirectory-functions/custom_functions.php
- The recent reviews widget ignores 1 star reviews - FIXED
> The recent reviews widget ignores 1 star reviews - FIXED

- change_log.txt
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/map-functions/map_on_add_listing_page.php
- Multiselect custom field "Display Type" option doesn't save on first attempt - FIXED
- Apostrophe in location name breaks the maps - FIXED
> Multiselect custom field "Display Type" option doesn't save on first attempt - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-functions/template_functions.php
- geodirectory_hooks_actions.php
> Minor parse error fixes

- geodirectory-functions/general_functions.php
- Minor change in popular post category count display - CHANGED
> Minor change in popular post category count display - CHANGED

- geodirectory-functions/general_functions.php
- Take buddypress user dashboard listings page as a author page
> Take buddypress user dashboard listings page as a author page

- change_log.txt
- geodirectory_template_actions.php
- Default image should not displayed on listing detail preview page - FIXED
> Default image should not displayed on listing detail preview page - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-assets/css/custom_field.css
- geodirectory-functions/custom_field_html.php
- geodirectory-functions/custom_fields_functions.php
- Changes to implement location import/export for multilocations - CHANGED
> Changes to implement location import/export for multilocations - CHANGED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/option-pages/design_settings_array.php
- geodirectory-admin/option-pages/general_settings_array.php
- geodirectory-admin/option-pages/notifications_settings_array.php
- geodirectory-admin/option-pages/permalink_settings_array.php
- geodirectory-functions/ajax_handler_functions.php
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/custom_functions.php
- geodirectory-functions/custom_taxonomy_hooks_actions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/geodir-class-session.php
- geodirectory-functions/helper_functions.php
- geodirectory-functions/listing_filters.php
- geodirectory-functions/location_functions.php
- geodirectory-functions/map-functions/get_markers.php
- geodirectory-functions/post_functions.php
- geodirectory-functions/shortcode_functions.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-functions/wp-session/class-recursive-arrayaccess.php
- geodirectory-functions/wp-session/class-wp-session.php
- geodirectory-functions/wp-session/index.php
- geodirectory-functions/wp-session/wp-session.php
- geodirectory-templates/add-listing.php
- geodirectory-templates/listing-listview.php
- geodirectory-templates/widget-listing-listview.php
- geodirectory-widgets/geodirectory_bestof_widget.php
- geodirectory_functions.php
- geodirectory_hooks_actions.php
- geodirectory_template_actions.php
- GeoDirectory Session class added to manage sessions - ADDED
> GeoDirectory Session class added to manage sessions - ADDED

- change_log.txt
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/listing_filters.php
- Deleting custom field not deletes the field from sorting fields table - FIXED
> Deleting custom field not deletes the field from sorting fields table - FIXED

- geodirectory-admin/option-pages/create_field.php
- geodirectory-functions/custom_functions.php
- geodirectory-functions/map-functions/get_markers.php
- geodirectory_hooks_actions.php
wp_get_image_editor() function used to fix image orientation
> wp_get_image_editor() function used to fix image orientation

- change_log.txt
- geodirectory-functions/custom_functions.php
- geodirectory_hooks_actions.php
- geodirectory_template_actions.php
- Hide tags and description fields if char limit set to ZERO for fields - CHANGED
> Hide tags and description fields if char limit set to ZERO for fields - CHANGED

- change_log.txt
- geodirectory-functions/location_functions.php
- geodirectory_template_tags.php
- country list in backend sorted a-z order
- Display cpt/category name in the advanced pagination info - CHANGED
> Display cpt/category name in the advanced pagination info - CHANGED

- change_log.txt
- geodirectory-admin/option-pages/general_settings_array.php
- geodirectory-functions/google_analytics.php
- geodirectory_hooks_actions.php
- Options added to check/refresh analytics data and to set time interval for auto refresh results - ADDED
> Options added to check/refresh analytics data and to set time interval for auto refresh results - ADDED

- change_log.txt
- geodirectory-admin/option-pages/title_meta_settings_array.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/shortcode_functions.php
- geodirectory_shortcodes.php
- Option added to show custom text when no listings found in gd_listings shortcode - CHANGED
- Page number variables added for titles & metas description - CHANGED
> Option added to show custom text when no listings found in gd_listings shortcode - CHANGED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- geodirectory-admin/admin_template_tags.php
- geodirectory-assets/css/admin.css
- geodirectory-functions/cat-meta-functions/Tax-meta-class.php
- geodirectory-functions/cat-meta-functions/cat_meta.php
- geodirectory-functions/signup_function.php
- geodirectory-templates/login_frm.php
- Forgot Password link not working - FIXED
- The category icon and default image uploader no longer working with WP 4.5 - FIXED
- Now able to set source category id for WPML translated categories in GD Import/Export - CHANGED
- GD Import/Export imports wrong latitudes values - FIXED
> Forgot Password link not working - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-admin/admin_hooks_actions.php
- jQuery chosen conflicts causes problem when add new region/city in backend add listing - FIXED
> jQuery chosen conflicts causes problem when add new region/city in backend add listing - FIXED

- change_log.txt
- geodirectory-functions/general_functions.php
- $_SERVER['SERVER_NAME'] returns empty host with nginx server - FIXED
> $_SERVER['SERVER_NAME'] returns empty host with nginx server - FIXED

- change_log.txt
- geodirectory_shortcodes.php
- New parameters post_type & category added to the listings map shortcode - CHANGED
> New parameters post_type & category added to the listings map shortcode - CHANGED

- change_log.txt
- geodirectory-functions/map-functions/map_on_add_listing_page.php
- geodirectory_template_tags.php
- The country code is undefined when default country is set and translated - FIXED
- Single quote in default city name causes problem in add new city - FIXED
> The country code is undefined when default country is set and translated - FIXED

- change_log.txt
- geodirectory-admin/admin_functions.php
- Fusion Builder jQuery chosen conflicts with GD jQuery chosen - FIXED
> Fusion Builder jQuery chosen conflicts with GD jQuery chosen - FIXED

- change_log.txt
- geodirectory_template_actions.php
- Hook added to enable/disable editor for description field - CHANGED
> Hook added to enable/disable editor for description field - CHANGED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/map-functions/map_functions.php
Category are not unticked on page refresh for map post type other than default - FIXED
> Category are not unticked on page refresh for map post type other than default - FIXED

- change_log.txt
- geodirectory-admin/option-pages/title_meta_settings_array.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/helper_functions.php
- geodirectory-functions/location_functions.php
- language.php
New title variables added to display country/region/city/neighbourhood - CHANGED
Some functions added for truncate, strlen, substr the text - ADDED
> New title variables added to display country/region/city/neighbourhood - CHANGED

- geodirectory-functions/comments_functions.php
change reviews tab title to comments for by default
> change reviews tab title to comments for by default

- change_log.txt
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/general_functions.php
> Listing slider widget breaks slider if on detail page - FIXED

- change_log.txt
- geodirectory-admin/option-pages/title_meta_settings_array.php
- geodirectory-functions/ajax_handler_functions.php
- geodirectory-functions/custom_functions.php
- geodirectory_hooks_actions.php
> Option added to disable overwrite by Yoast SEO titles & metas on GD pages - ADDED

- change_log.txt
- geodirectory-functions/general_functions.php
- Sort CPT taxonomy in popular categories widget - CHANGED
> Sort CPT taxonomy in popular categories widget - CHANGED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-functions/custom_fields_functions.php
- geodirectory-functions/custom_functions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/helper_functions.php
- geodirectory-functions/listing_filters.php
- geodirectory-functions/map-functions/map_functions.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-functions/user_functions.php
- geodirectory-widgets/geodirectory_bestof_widget.php
- geodirectory-widgets/geodirectory_listing_slider_widget.php
- geodirectory-widgets/geodirectory_popular_widget.php
- geodirectory_hooks_actions.php
- geodirectory_shortcodes.php
- geodirectory_template_actions.php
- upgrade.php
- In [gd_listings] shortcode if category has no posts then it shows all the results - FIXED
See: https://wpgeodirectory.com/support/topic/shortcode-gd_listings-showing-all-places-2/
> In [gd_listings] shortcode if category has no posts then it shows all the results - FIXED

- change_log.txt
- geodirectory_shortcodes.php
[gd_popular_post_view] shortcode character_count=0 not working - FIXED
See: https://wpgeodirectory.com/support/topic/force-excerpt-at-0-in-core-shortcodes/
> [gd_popular_post_view] shortcode character_count=0 not working - FIXED

- change_log.txt
- geodirectory-functions/cat-meta-functions/Tax-meta-class.php
- geodirectory-functions/cat-meta-functions/cat_meta.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/listing_filters.php
- geodirectory-functions/shortcode_functions.php
- geodirectory_shortcodes.php
- Categories icon urls are broken if site moved from http to https - FIXED
See: https://wpgeodirectory.com/support/topic/issues-with-broken-category-defaulticon-images/
> Categories icon urls are broken if site moved from http to https - FIXED

- geodirectory-languages/geodirectory-en_US.po
- language.php
Fixing an error I noticed in the form validation messaging
> Fixing spelling error in form validation message.

- change_log.txt
- geodirectory-functions/geodir-class-session.php
- geodirectory-functions/wp-session/class-recursive-arrayaccess.php
- geodirectory-functions/wp-session/class-wp-session-utils.php
- geodirectory-functions/wp-session/class-wp-session.php
- geodirectory-functions/wp-session/wp-cli.php
- geodirectory-functions/wp-session/wp-session.php
- Security vulnerability updates in the WP Session - CHANGED
> Security vulnerability updates in the WP Session - CHANGED

- change_log.txt
- geodirectory-functions/custom_fields_output_functions.php
- New hook added to filter address fields being displayed - ADDED
> New hook added to filter address fields being displayed - ADDED

- change_log.txt
- geodirectory-admin/admin_functions.php
- geodirectory-functions/custom_functions.php
- geodirectory-functions/general_functions.php
- geodirectory-functions/listing_filters.php
- geodirectory-functions/map-functions/map_functions.php
- geodirectory-functions/shortcode_functions.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-functions/template_functions.php
- geodirectory_hooks_actions.php
- geodirectory_shortcodes.php
- Don't translate GD post types/taxonomies if disabled in WPML settings - CHANGED
> Don't translate GD post types/taxonomies if disabled in WPML settings - CHANGED

- change_log.txt
- geodirectory_hooks_actions.php
Fix #419 
- Theme My Login compatibility fix - FIXED
> Theme My Login compatibility fix - FIXED

- change_log.txt
- geodirectory-admin/admin_hooks_actions.php
> Disable quick edit links for GD CPTs - CHANGED

- change_log.txt
- geodirectory-functions/listing_filters.php
- geodirectory-functions/taxonomy_functions.php
- geodirectory-templates/geodir-signup.php
- geodirectory_hooks_actions.php
- Widget listing should show nearest results when location filter enabled and lat/lon set - CHANGED
- On login/signup page redirect_to parameter not working for logged user - FIXED
> Widget listing should show nearest results when location filter enabled and lat/lon set - CHANGED

- change_log.txt
- geodirectory_shortcodes.php
Topic: https://wpgeodirectory.com/support/topic/gd-listing-shortcode/#post-391275
> gd_listings shortcode shows all listings if post_author has no listings - FIXED

- change_log.txt
- geodirectory-functions/shortcode_functions.php
See https://wpgeodirectory.com/support/topic/listing-shortcode/#post-397559
> listing_width parameter does not working in gd_listings shortcode FIXED

- change_log.txt
- geodirectory-functions/general_functions.php
- geodirectory-functions/listing_filters.php
See https://wpgeodirectory.com/support/topic/popular-post-view-widget-view-all-2/
> View all link should go to search page with near me selected - CHANGED

- change_log.txt
- geodirectory-functions/general_functions.php
See https://wpgeodirectory.com/support/topic/put-more-category-in-the-beginning/#post-399660
> category_restrict parameter not hiding the text More Categories/Less Categories - FIXED

- change_log.txt
- geodirectory-admin/admin_hooks_actions.php
See https://wpgeodirectory.com/support/topic/yoast-8-0-conflict/#post-442406
> Yoast v8.x shows error on backend edit listing page - FIXED

- change_log.txt
- geodirectory-functions/custom_functions.php
See https://wpgeodirectory.com/support/topic/search-button-not-showing/page/2/#post-466002
> Sometime search button shows font-awesome icon html - FIXED
